# Generated by Django 3.1.4 on 2021-01-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='icon',
            field=models.CharField(default='', max_length=50, verbose_name='图标'),
        ),
    ]
