# Generated by Django 3.1.4 on 2021-01-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_category_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
    ]
